[package]
name = "finalproject"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }
nalgebra = "0.32"
linfa = "0.7"
linfa-linear = "0.7"
ndarray = "0.15"
